// <auto-generated />
using System;
using HrPanel.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HrPanel.Persistence.Database.Migrations
{
    [DbContext(typeof(HrDbContext))]
    [Migration("20260721125010_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hr")
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HrPanel.Domain.Assets.Asset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssetTag")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("AssetTypeId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imei")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ServiceNumber")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("AssetTag")
                        .IsUnique()
                        .HasDatabaseName("UX_Assets_AssetTag")
                        .HasFilter("[AssetTag] IS NOT NULL");

                    b.HasIndex("AssetTypeId")
                        .HasDatabaseName("IX_Assets_AssetTypeId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Imei")
                        .IsUnique()
                        .HasDatabaseName("UX_Assets_Imei")
                        .HasFilter("[Imei] IS NOT NULL");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Assets_SerialNumber")
                        .HasFilter("[SerialNumber] IS NOT NULL");

                    b.HasIndex("ServiceNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Assets_ServiceNumber")
                        .HasFilter("[ServiceNumber] IS NOT NULL");

                    b.ToTable("Assets", "asset");
                });

            modelBuilder.Entity("HrPanel.Domain.Assets.AssetType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameEn")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameFa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetTypes_Code");

                    b.ToTable("AssetTypes", "asset");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "TDLTE_MODEM",
                            IsActive = true,
                            NameEn = "TD-LTE Modem",
                            NameFa = "مودم TD-LTE"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "SIM_CARD",
                            IsActive = true,
                            NameEn = "SIM Card",
                            NameFa = "سیم‌کارت"
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "LAPTOP",
                            IsActive = true,
                            NameEn = "Laptop",
                            NameFa = "لپ‌تاپ"
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "ACCESS_CARD",
                            IsActive = true,
                            NameEn = "Access Card",
                            NameFa = "کارت تردد"
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "MOBILE_PHONE",
                            IsActive = true,
                            NameEn = "Mobile Phone",
                            NameFa = "تلفن همراه"
                        },
                        new
                        {
                            Id = (short)6,
                            Code = "OTHER",
                            IsActive = true,
                            NameEn = "Other",
                            NameFa = "سایر"
                        });
                });

            modelBuilder.Entity("HrPanel.Domain.Assets.EmployeeAssetAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("AssignedAt")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("ReturnedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeeAssetAssignments_CurrentAsset")
                        .HasFilter("[ReturnedAt] IS NULL");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_EmployeeAssetAssignments_EmployeeId");

                    b.ToTable("EmployeeAssetAssignments", "asset", t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeAssetAssignments_DateRange", "[ReturnedAt] IS NULL OR [ReturnedAt] >= [AssignedAt]");
                        });
                });

            modelBuilder.Entity("HrPanel.Domain.Employees.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("LegacyGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacyUserId")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Employees_EmployeeNumber");

                    b.HasIndex("LegacyGuid")
                        .IsUnique()
                        .HasDatabaseName("UX_Employees_LegacyGuid")
                        .HasFilter("[LegacyGuid] IS NOT NULL");

                    b.HasIndex("LegacyUserId")
                        .HasDatabaseName("IX_Employees_LegacyUserId")
                        .HasFilter("[LegacyUserId] IS NOT NULL");

                    b.ToTable("Employees", "hr", t =>
                        {
                            t.HasCheckConstraint("CK_Employees_EmployeeNumber_NotEmpty", "LEN(LTRIM(RTRIM([EmployeeNumber]))) > 0");
                        });
                });

            modelBuilder.Entity("HrPanel.Domain.Employees.EmployeeContact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(320)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_EmployeeContacts_EmployeeId");

                    b.HasIndex("EmployeeId", "Type")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeeContacts_PrimaryByType")
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("EmployeeContacts", "hr");
                });

            modelBuilder.Entity("HrPanel.Domain.Employees.EmployeeDependent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmergencyPhone")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsEmergencyContact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<short>("RelationshipType")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_EmployeeDependents_EmployeeId");

                    b.ToTable("EmployeeDependents", "hr");
                });

            modelBuilder.Entity("HrPanel.Domain.Employees.EmployeeEducation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DegreeTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("FieldOfStudy")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly?>("GraduationDate")
                        .HasColumnType("date");

                    b.Property<string>("InstitutionName")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsHighestDegree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeeEducations_HighestDegree")
                        .HasFilter("[IsHighestDegree] = 1");

                    b.ToTable("EmployeeEducations", "hr");
                });

            modelBuilder.Entity("HrPanel.Domain.Employees.EmployeeIdentifier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_EmployeeIdentifiers_EmployeeId");

                    b.HasIndex("Type", "Value")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeeIdentifiers_ActiveValue")
                        .HasFilter("[EffectiveTo] IS NULL");

                    b.ToTable("EmployeeIdentifiers", "hr");
                });

            modelBuilder.Entity("HrPanel.Domain.Employees.EmployeePersonalDetails", b =>
                {
                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FatherName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FatherNationalCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstNameFa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("Gender")
                        .HasColumnType("smallint");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastNameFa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("MaritalStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.HasKey("EmployeeId");

                    b.HasIndex("NationalCode")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeePersonalDetails_NationalCode")
                        .HasFilter("[NationalCode] IS NOT NULL");

                    b.ToTable("EmployeePersonalDetails", "hr");
                });

            modelBuilder.Entity("HrPanel.Domain.Employment.DisciplinaryAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EmployeeId", "StartDate")
                        .HasDatabaseName("IX_DisciplinaryActions_Employee_Date");

                    b.ToTable("DisciplinaryActions", "hr", t =>
                        {
                            t.HasCheckConstraint("CK_DisciplinaryActions_DateRange", "[EndDate] IS NULL OR [EndDate] >= [StartDate]");
                        });
                });

            modelBuilder.Entity("HrPanel.Domain.Employment.EmployeeAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short>("Context")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<long>("EmploymentId")
                        .HasColumnType("bigint");

                    b.Property<short?>("JobLevelId")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkLocationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("JobLevelId");

                    b.HasIndex("OrganizationUnitId");

                    b.HasIndex("PositionId");

                    b.HasIndex("WorkLocationId");

                    b.HasIndex("EmploymentId", "Context")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeeAssignments_CurrentByContext")
                        .HasFilter("[EffectiveTo] IS NULL");

                    b.ToTable("EmployeeAssignments", "hr", t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeAssignments_DateRange", "[EffectiveTo] IS NULL OR [EffectiveTo] >= [EffectiveFrom]");
                        });
                });

            modelBuilder.Entity("HrPanel.Domain.Employment.EmployeeRelationship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short>("Context")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("RelatedEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RelatedExternalPersonId")
                        .HasColumnType("bigint");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("RelatedEmployeeId");

                    b.HasIndex("RelatedExternalPersonId");

                    b.HasIndex("EmployeeId", "Type", "Context")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeeRelationships_CurrentByContext")
                        .HasFilter("[EffectiveTo] IS NULL");

                    b.ToTable("EmployeeRelationships", "hr", t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeRelationships_DateRange", "[EffectiveTo] IS NULL OR [EffectiveTo] >= [EffectiveFrom]");

                            t.HasCheckConstraint("CK_EmployeeRelationships_NotSelf", "[RelatedEmployeeId] IS NULL OR [RelatedEmployeeId] <> [EmployeeId]");

                            t.HasCheckConstraint("CK_EmployeeRelationships_SingleRelatedParty", "([RelatedEmployeeId] IS NOT NULL AND [RelatedExternalPersonId] IS NULL) OR ([RelatedEmployeeId] IS NULL AND [RelatedExternalPersonId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("HrPanel.Domain.Employment.Employment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short?>("ContractTermMonths")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<short>("EmploymentStatusId")
                        .HasColumnType("smallint");

                    b.Property<short>("EmploymentTypeId")
                        .HasColumnType("smallint");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UX_Employments_CurrentByEmployee")
                        .HasFilter("[EndDate] IS NULL");

                    b.HasIndex("EmploymentStatusId")
                        .HasDatabaseName("IX_Employments_EmploymentStatusId");

                    b.HasIndex("EmploymentTypeId")
                        .HasDatabaseName("IX_Employments_EmploymentTypeId");

                    b.ToTable("Employments", "hr", t =>
                        {
                            t.HasCheckConstraint("CK_Employments_ContractTermMonths", "[ContractTermMonths] IS NULL OR ([ContractTermMonths] >= 1 AND [ContractTermMonths] <= 120)");

                            t.HasCheckConstraint("CK_Employments_DateRange", "[EndDate] IS NULL OR [EndDate] >= [StartDate]");
                        });
                });

            modelBuilder.Entity("HrPanel.Domain.Employment.EmploymentStatus", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameEn")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameFa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_EmploymentStatuses_Code");

                    b.ToTable("EmploymentStatuses", "hr");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "ACTIVE",
                            IsActive = true,
                            NameEn = "Active",
                            NameFa = "فعال"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "INACTIVE",
                            IsActive = true,
                            NameEn = "Inactive",
                            NameFa = "غیرفعال"
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "TERMINATED",
                            IsActive = true,
                            NameEn = "Terminated",
                            NameFa = "خاتمه همکاری"
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "RESIGNED",
                            IsActive = true,
                            NameEn = "Resigned",
                            NameFa = "استعفا"
                        });
                });

            modelBuilder.Entity("HrPanel.Domain.Employment.EmploymentType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameEn")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameFa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_EmploymentTypes_Code");

                    b.ToTable("EmploymentTypes", "hr");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "PERMANENT",
                            IsActive = true,
                            NameEn = "Permanent",
                            NameFa = "رسمی"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "CONTRACT",
                            IsActive = true,
                            NameEn = "Contract",
                            NameFa = "قراردادی"
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "VENDOR",
                            IsActive = true,
                            NameEn = "Vendor",
                            NameFa = "پیمانکاری"
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "PROJECT",
                            IsActive = true,
                            NameEn = "Project",
                            NameFa = "پروژه‌ای"
                        });
                });

            modelBuilder.Entity("HrPanel.Domain.Employment.ExternalPerson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LegacyUsername")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("LegacyUsername")
                        .IsUnique()
                        .HasDatabaseName("UX_ExternalPersons_LegacyUsername")
                        .HasFilter("[LegacyUsername] IS NOT NULL");

                    b.ToTable("ExternalPersons", "hr");
                });

            modelBuilder.Entity("HrPanel.Domain.Organization.JobLevel", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<short>("Rank")
                        .HasColumnType("smallint");

                    b.Property<string>("TitleEn")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TitleFa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_JobLevels_Code");

                    b.HasIndex("Rank")
                        .HasDatabaseName("IX_JobLevels_Rank");

                    b.ToTable("JobLevels", "org", t =>
                        {
                            t.HasCheckConstraint("CK_JobLevels_Rank", "[Rank] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "INTERN",
                            IsActive = true,
                            Rank = (short)1,
                            TitleEn = "Intern",
                            TitleFa = "کارآموز"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "JUNIOR",
                            IsActive = true,
                            Rank = (short)2,
                            TitleEn = "Junior",
                            TitleFa = "کارشناس تازه‌کار"
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "MID",
                            IsActive = true,
                            Rank = (short)3,
                            TitleEn = "Mid-Level",
                            TitleFa = "کارشناس"
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "SENIOR",
                            IsActive = true,
                            Rank = (short)4,
                            TitleEn = "Senior",
                            TitleFa = "کارشناس ارشد"
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "LEAD",
                            IsActive = true,
                            Rank = (short)5,
                            TitleEn = "Lead",
                            TitleFa = "سرپرست"
                        },
                        new
                        {
                            Id = (short)6,
                            Code = "MANAGER",
                            IsActive = true,
                            Rank = (short)6,
                            TitleEn = "Manager",
                            TitleFa = "مدیر"
                        });
                });

            modelBuilder.Entity("HrPanel.Domain.Organization.OrganizationUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameEn")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameFa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<short>("OrganizationUnitTypeId")
                        .HasColumnType("smallint");

                    b.Property<long?>("ParentOrganizationUnitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_OrganizationUnits_Code");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("OrganizationUnitTypeId")
                        .HasDatabaseName("IX_OrganizationUnits_TypeId");

                    b.HasIndex("ParentOrganizationUnitId")
                        .HasDatabaseName("IX_OrganizationUnits_ParentId");

                    b.ToTable("OrganizationUnits", "org", t =>
                        {
                            t.HasCheckConstraint("CK_OrganizationUnits_NotOwnParent", "[ParentOrganizationUnitId] IS NULL OR [ParentOrganizationUnitId] <> [Id]");
                        });
                });

            modelBuilder.Entity("HrPanel.Domain.Organization.OrganizationUnitType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<short>("HierarchyOrder")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameEn")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameFa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_OrganizationUnitTypes_Code");

                    b.HasIndex("HierarchyOrder")
                        .HasDatabaseName("IX_OrganizationUnitTypes_HierarchyOrder");

                    b.ToTable("OrganizationUnitTypes", "org", t =>
                        {
                            t.HasCheckConstraint("CK_OrganizationUnitTypes_HierarchyOrder", "[HierarchyOrder] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "COMPANY",
                            HierarchyOrder = (short)1,
                            IsActive = true,
                            NameEn = "Company",
                            NameFa = "شرکت"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "DIVISION",
                            HierarchyOrder = (short)2,
                            IsActive = true,
                            NameEn = "Division",
                            NameFa = "معاونت"
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "SUBDIVISION",
                            HierarchyOrder = (short)3,
                            IsActive = true,
                            NameEn = "Subdivision",
                            NameFa = "زیرمعاونت"
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "DEPARTMENT",
                            HierarchyOrder = (short)4,
                            IsActive = true,
                            NameEn = "Department",
                            NameFa = "اداره"
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "SECTION",
                            HierarchyOrder = (short)5,
                            IsActive = true,
                            NameEn = "Section",
                            NameFa = "بخش"
                        },
                        new
                        {
                            Id = (short)6,
                            Code = "UNIT",
                            HierarchyOrder = (short)6,
                            IsActive = true,
                            NameEn = "Unit",
                            NameFa = "واحد"
                        });
                });

            modelBuilder.Entity("HrPanel.Domain.Organization.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TitleEn")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TitleFa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Positions_Code");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("Positions", "org");
                });

            modelBuilder.Entity("HrPanel.Domain.Organization.WorkLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameEn")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameFa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_WorkLocations_Code");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Province", "City")
                        .HasDatabaseName("IX_WorkLocations_Province_City");

                    b.ToTable("WorkLocations", "org");
                });

            modelBuilder.Entity("HrPanel.Domain.Scheduling.EmployeeScheduleAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<long>("EmploymentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("WorkScheduleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EmploymentId")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeeScheduleAssignments_CurrentEmployment")
                        .HasFilter("[EffectiveTo] IS NULL");

                    b.HasIndex("WorkScheduleId")
                        .HasDatabaseName("IX_EmployeeScheduleAssignments_WorkScheduleId");

                    b.HasIndex("EmploymentId", "EffectiveFrom")
                        .HasDatabaseName("IX_EmployeeScheduleAssignments_Employment_Date");

                    b.ToTable("EmployeeScheduleAssignments", "attendance", t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeScheduleAssignments_DateRange", "[EffectiveTo] IS NULL OR [EffectiveTo] >= [EffectiveFrom]");
                        });
                });

            modelBuilder.Entity("HrPanel.Domain.Scheduling.Shift", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(0)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameEn")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameFa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(0)");

                    b.Property<decimal>("WorkHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Shifts_Code");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("Shifts", "attendance", t =>
                        {
                            t.HasCheckConstraint("CK_Shifts_DifferentStartAndEndTime", "[StartTime] <> [EndTime]");

                            t.HasCheckConstraint("CK_Shifts_WorkHours", "[WorkHours] > 0 AND [WorkHours] <= 24");
                        });
                });

            modelBuilder.Entity("HrPanel.Domain.Scheduling.WorkSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameFa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("ShiftId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("WorkDaysPerWeek")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_WorkSchedules_Code");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("IX_WorkSchedules_ShiftId");

                    b.ToTable("WorkSchedules", "attendance", t =>
                        {
                            t.HasCheckConstraint("CK_WorkSchedules_WorkDaysPerWeek", "[WorkDaysPerWeek] > 0 AND [WorkDaysPerWeek] <= 7");
                        });
                });

            modelBuilder.Entity("HrPanel.Persistence.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8137cf2-5b8b-4c4e-9eaa-899a0430476a"),
                            ConcurrencyStamp = "7A418004-C400-4B97-AAB4-9A9D7789C114",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("0a40cd90-4bb6-4f98-8ce3-082ecfcb1bcb"),
                            ConcurrencyStamp = "1AA90549-3B27-4015-9CC8-CBF6B931671A",
                            Name = "HrStaff",
                            NormalizedName = "HRSTAFF"
                        });
                });

            modelBuilder.Entity("HrPanel.Persistence.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_EmployeeId")
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("HrPanel.Persistence.LegacyImport.LegacyEmployeeImportRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternateEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchiveNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractTerm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DivisionCr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherNationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstNameFa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imei")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("ImportStatus")
                        .HasColumnType("smallint");

                    b.Property<long?>("ImportedEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("JobLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastNameFa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegacyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerUsername2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerUsername3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerUsername4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerUsernameCr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerUsernameCr2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerUsernameCr3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerUsernameCr4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pilot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionCr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionHr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProvinceWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QaUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeniorManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SourceUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpouseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpouseNationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartWorkFirst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubDivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmitBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmitDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorUsernameCr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Td")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarningDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarningEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarningStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkLocation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ImportStatus")
                        .HasDatabaseName("IX_LegacyEmployeeImportRows_Status");

                    b.HasIndex("ImportedEmployeeId")
                        .HasDatabaseName("IX_LegacyEmployeeImportRows_ImportedEmployeeId");

                    b.HasIndex("BatchId", "SourceRowNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_LegacyEmployeeImportRows_Batch_Row");

                    b.ToTable("LegacyEmployeeImportRows", "staging");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "identity");
                });

            modelBuilder.Entity("HrPanel.Domain.Assets.Asset", b =>
                {
                    b.HasOne("HrPanel.Domain.Assets.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetType");
                });

            modelBuilder.Entity("HrPanel.Domain.Assets.EmployeeAssetAssignment", b =>
                {
                    b.HasOne("HrPanel.Domain.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrPanel.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HrPanel.Domain.Employees.EmployeeContact", b =>
                {
                    b.HasOne("HrPanel.Domain.Employees.Employee", "Employee")
                        .WithMany("Contacts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HrPanel.Domain.Employees.EmployeeDependent", b =>
                {
                    b.HasOne("HrPanel.Domain.Employees.Employee", "Employee")
                        .WithMany("Dependents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HrPanel.Domain.Employees.EmployeeEducation", b =>
                {
                    b.HasOne("HrPanel.Domain.Employees.Employee", "Employee")
                        .WithMany("EducationRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HrPanel.Domain.Employees.EmployeeIdentifier", b =>
                {
                    b.HasOne("HrPanel.Domain.Employees.Employee", "Employee")
                        .WithMany("Identifiers")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HrPanel.Domain.Employees.EmployeePersonalDetails", b =>
                {
                    b.HasOne("HrPanel.Domain.Employees.Employee", "Employee")
                        .WithOne("PersonalDetails")
                        .HasForeignKey("HrPanel.Domain.Employees.EmployeePersonalDetails", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HrPanel.Domain.Employment.DisciplinaryAction", b =>
                {
                    b.HasOne("HrPanel.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HrPanel.Domain.Employment.EmployeeAssignment", b =>
                {
                    b.HasOne("HrPanel.Domain.Employment.Employment", "Employment")
                        .WithMany("Assignments")
                        .HasForeignKey("EmploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrPanel.Domain.Organization.JobLevel", "JobLevel")
                        .WithMany()
                        .HasForeignKey("JobLevelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HrPanel.Domain.Organization.OrganizationUnit", "OrganizationUnit")
                        .WithMany()
                        .HasForeignKey("OrganizationUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HrPanel.Domain.Organization.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HrPanel.Domain.Organization.WorkLocation", "WorkLocation")
                        .WithMany()
                        .HasForeignKey("WorkLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employment");

                    b.Navigation("JobLevel");

                    b.Navigation("OrganizationUnit");

                    b.Navigation("Position");

                    b.Navigation("WorkLocation");
                });

            modelBuilder.Entity("HrPanel.Domain.Employment.EmployeeRelationship", b =>
                {
                    b.HasOne("HrPanel.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrPanel.Domain.Employees.Employee", "RelatedEmployee")
                        .WithMany()
                        .HasForeignKey("RelatedEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HrPanel.Domain.Employment.ExternalPerson", "RelatedExternalPerson")
                        .WithMany()
                        .HasForeignKey("RelatedExternalPersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("RelatedEmployee");

                    b.Navigation("RelatedExternalPerson");
                });

            modelBuilder.Entity("HrPanel.Domain.Employment.Employment", b =>
                {
                    b.HasOne("HrPanel.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrPanel.Domain.Employment.EmploymentStatus", "EmploymentStatus")
                        .WithMany()
                        .HasForeignKey("EmploymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrPanel.Domain.Employment.EmploymentType", "EmploymentType")
                        .WithMany()
                        .HasForeignKey("EmploymentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("EmploymentStatus");

                    b.Navigation("EmploymentType");
                });

            modelBuilder.Entity("HrPanel.Domain.Organization.OrganizationUnit", b =>
                {
                    b.HasOne("HrPanel.Domain.Organization.OrganizationUnitType", "OrganizationUnitType")
                        .WithMany()
                        .HasForeignKey("OrganizationUnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrPanel.Domain.Organization.OrganizationUnit", "ParentOrganizationUnit")
                        .WithMany("Children")
                        .HasForeignKey("ParentOrganizationUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OrganizationUnitType");

                    b.Navigation("ParentOrganizationUnit");
                });

            modelBuilder.Entity("HrPanel.Domain.Scheduling.EmployeeScheduleAssignment", b =>
                {
                    b.HasOne("HrPanel.Domain.Employment.Employment", "Employment")
                        .WithMany()
                        .HasForeignKey("EmploymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrPanel.Domain.Scheduling.WorkSchedule", "WorkSchedule")
                        .WithMany()
                        .HasForeignKey("WorkScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employment");

                    b.Navigation("WorkSchedule");
                });

            modelBuilder.Entity("HrPanel.Domain.Scheduling.WorkSchedule", b =>
                {
                    b.HasOne("HrPanel.Domain.Scheduling.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("HrPanel.Persistence.Identity.ApplicationUser", b =>
                {
                    b.HasOne("HrPanel.Domain.Employees.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("HrPanel.Persistence.Identity.ApplicationUser", "EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("HrPanel.Persistence.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HrPanel.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HrPanel.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("HrPanel.Persistence.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrPanel.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HrPanel.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HrPanel.Domain.Employees.Employee", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Dependents");

                    b.Navigation("EducationRecords");

                    b.Navigation("Identifiers");

                    b.Navigation("PersonalDetails");
                });

            modelBuilder.Entity("HrPanel.Domain.Employment.Employment", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("HrPanel.Domain.Organization.OrganizationUnit", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
